### ISSUE TITLE
Stroke is not properly rendered in points

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/renderer-prototype#184]
The point `width` is not updated with the `strokeWidth` so if `strokeColor` contains opacity it shows the hidden point with the full size.
![selection_084](https://user-images.githubusercontent.com/2227572/37531527-be78f858-293c-11e8-9131-161ee656aba0.png)

~IMO the default behavior should be something like~
![selection_088](https://user-images.githubusercontent.com/2227572/37531579-de81f712-293c-11e8-8106-9ab4389e1c6f.png)

Also I have observed that this point has `width: 50 strokeWidth: 50`. I would expect the border covering all the point with this configuration, but it doesn't.

@makella we should define first how this should look like and then change it in the shader. What do you think?

**Comment by makella** [comment]
@Jesus89 good catch!!

First, I want to say this is important for general point maps but with the addition of being able to vary stroke width based on any expression, this could become even more noticeable.

Here is an example I was just looking at:

![screen shot 2018-03-16 at 10 52 48 am](https://user-images.githubusercontent.com/1566273/37533699-349502dc-2908-11e8-998d-26bd1f3e9faa.png)

What it looks like to me is that the drawing order is first the stroke, then the marker.

In your example, I'm not sure what it would look like when opacity is applied to the stroke.

![selection_088](https://user-images.githubusercontent.com/2227572/37531579-de81f712-293c-11e8-8106-9ab4389e1c6f.png)

Since the stroke is meant to outline the marker, is it possible to have it draw around the marker where the stroke width would start from the edge of the marker and go out?

I think that will be the only way to avoid the issue on a wider scale

For example:
![screen shot 2018-03-16 at 11 03 56 am](https://user-images.githubusercontent.com/1566273/37534418-68f20e4c-290a-11e8-86cf-fff0f253cc98.png)

And with opacity:
![screen shot 2018-03-16 at 11 04 14 am](https://user-images.githubusercontent.com/1566273/37534432-6e6019aa-290a-11e8-94f5-6136e0eb302c.png)

Also, is there a place where we can see the options with the shaders?

**Comment by makella** [comment]
ok! go for it.

let's do some testing when implemented and if we need to make changes, we can evaluate then.

thanks!

**Comment by makella** [comment]
actually, is there a way where the stroke doesn't cover the circle? I think for me, that's the biggest thing. Where we don't get that brown color.

If the stroke was coming from the outside of the marker, vs. the center, I wonder if that would make a difference?

**Comment by makella** [comment]
![screen shot 2018-03-19 at 8 04 21 am](https://user-images.githubusercontent.com/1566273/37600167-29b298ac-2b4c-11e8-9e10-3a940e67d94f.png)

a demonstration of the different places an outline can come from. 

width: 85 (gray)
stroke: 20 w/ 50% transparency (purple)

**Comment by Jesus89** [comment]
Hi @makella.

> actually, is there a way where the stroke doesn't cover the circle? I think for me, that's the biggest thing. 

We can do it but it seems that the standard behavior for vector rendering (SVG) is the first one. It seems that this is also the behavior in mapnik:

![selection_091](https://user-images.githubusercontent.com/2227572/37668090-e7e92c06-2c63-11e8-89c4-1715ff2afce0.png)

**Comment by makella** [comment]
yep, it is default mapnik... that's why i was curious if we could improve!

anyway, do what you think is best and we can go from there.

thanks!

**Comment by makella** [comment]
related to text, but the exact same concepts demonstrating and explaining the different stroke positions. Interesting insight on keeping the integrity of the original shape based on stroke choice.

https://css-tricks.com/text-stroke-stuck-middle/

**Comment by Jesus89** [comment]
I have created a PR to fix the bug with the size: https://github.com/CartoDB/renderer-prototype/pull/206

**Comment by Jesus89** [comment]
Closed by: https://github.com/CartoDB/renderer-prototype/pull/206#pullrequestreview-106059272
