### ISSUE TITLE
Create Feature object

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/renderer-prototype#201]
Related to #61

**Comment by davidmanzanares** [comment]
I first tried creating a Feature class, but then, I reilase it could be complex to explain to users in the docs. It can be done with things like `@hideconstructor`, but it seemed artificial to me.

I finally "added it" by documenting a `Feature` object type, similar to `CartoError`. In this way it is more clear that a `Feature` is a type of something that we will provide, instead of a class that the user can instantiate in order to do something.
