### ISSUE TITLE
Line rendering artifacts

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#36]
@dv343 

Take a look at this map with a high density of lines... the rendering of lines is dashed and there are horizontal artifacts showing as you zoom in

https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoiYWxsc3Rvcm1zX2lidHJhY3NfYWxsX2xpbmVzX3YwM3IwOSIsImIiOiI0ZDIxMjM3NTM4NmJhZjFhMDliYjgyNjA4YzY0ODIxODhkYTNhNWIwIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJjYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoJGJhc2luLGJvbGQpXG53aWR0aDogMC41XG5cblxuXG5cblxuXG4iLCJmIjp7ImxuZyI6MTEzLjQ3MTU4ODE3NjcwOTQ3LCJsYXQiOjE0LjYwMjc4MzY4MzQwMTk5NX0sImciOjEuOTQ0NTc2MTA2NTkxMDU1fQ==

**Comment by davidmanzanares** [comment]
This is due to the way we render lines. Basically, we just render triangles and rely on the browser anti-aliasing, which must be also enabled by the context creator (probably MGL).

Apart from using lines with width greater or equal to `1` there is no easy fix.

Possible fixes includes rendering lines with some alpha blending near the edge and rendering lines with distance fields.

**Comment by makella** [comment]
hmmmm... this could get tricky then. when you have a high density of lines, a line-width of `1` will be too much and will look like a mush.

the next step in designing the lines for a NUMERIC attribute would be things like applying transparency, varying the line-width and potentially applying a sequential scheme...

but for categories, other than transparency (and potentially using the line width to apply line-weights and vary the transparency based on that too which is a more advanced operation) the basic use case would be assigned different colors with a qualitative scheme...

i'll try with some not-so-dense lines to see what we can do with what we have, but definitely, think the broken lines and the holes that appear are not the rendering that we want!
