### ISSUE TITLE
Basic API definition

### ISSUE THREAD

**Issue by rochoa** [CartoDB/renderer-prototype#43]
Although there is some initial work on the public API in https://docs.google.com/document/d/1ZewIIQ49qbIB1cEwuWh615JCNZi13uJl0OXR1QLNS7w/edit, we need to define the API for, at least, the following components:

(Edit: @Jesus89)

 - [x] Source + unit tests + docs
 - [x] Style + unit tests + docs
 - [x] Layer + unit tests + docs
 - [x] Defaults: Auth and config (API endpoint, etc) + unit tests + docs
 - [x] Add CartoErrors (error handling) + docs

Also, this should define how we are gonna test the API.
 - [x] Define how we test input data in public API.
 - [x] What library we are gonna use for those tests.

**Comment by IagoLast** [comment]
My two cents about how to handle this:

- Detail use-cases first (including error handling). For each one:
  - Create an example
  - Create unit tests
  - Add jsdoc documentation

cc @davidmanzanares @Jesus89

**Comment by Jesus89** [comment]
I'm going to take this one.

This is the main [API document](https://docs.google.com/document/d/1ZewIIQ49qbIB1cEwuWh615JCNZi13uJl0OXR1QLNS7w).

### Source

```js
const source = new carto.source.Dataset('table'); // use default auth
const source = new carto.source.Dataset('table', auth);
const source = new carto.source.SQL('SELECT * FROM table'); // default auth
const source = new carto.source.SQL('SELECT * FROM table', auth);
```

### Style

```js
const style = new carto.Style(`
  color: ramp(jenks($price, float(3)), PRISM)
`);
const s = carto.style.expression;
const style = new carto.Style({
  color: s.ramp(s.jenks(s.prop('price'), s.float(3)), s.PRISM)
});
```

### Layer

```js
var layer = new carto.Layer(id, mySource, myStyle);
layer.addTo(map);
```

### Default Auth/config

```js
carto.setDefaultAuth({
  user: 'cartojs-test',
  apiKey: '123456789012345678901234567890123456789'
});
carto.setDefaultConfig({
  serverUrl: 'https://{user}.cartox.com'
});
```

I will start adding the code and the documentation. As soon as the `Tests PR` is merged I will add also the unit tests.

**Comment by Jesus89** [comment]
I open a "thread" here regarding to Style and Layer objects. As in CARTO.js, we have now only one type of Style and one type of Layer, but in order to have the same API structure and coherence than CARTO.js, I would add the following objects:

```js
carto.style.Base -> carto.style.Style
carto.layer.Base -> carto.layer.Layer
```

So in the documentation, the Layer object has the inputs `carto.source.Base` and `carto.style.Base`. This may sound redundant but it matches with the plan for CARTO.js API and it allows easy extension for the API and may be a future convergence of the APIs.

**Comment by davidmanzanares** [comment]
We do not have plans for future convergence. This is repeated namespace and it is clearly not consistent with the Mapbox GL way.

There is only one layer type and one style type, therefore, there is no need to add a useless namespace.

You may want to check Mapbox GL docs.

**Comment by Jesus89** [comment]
It is not discarded a future convergence with CARTO.js. We need to think about that and put some effort on it.

This library should be independent from Mapbox. Now it works with Mapbox GL but in the future may work with other libraries ([openlayers](https://openlayers.org/en/latest/apidoc/), ...). Because of that, instead of following the "Mapbox" styleguide we should follow the "CARTO" styleguide.

**Comment by IagoLast** [comment]
### Namespaces
I prefer to not add unnecessary namespaces

### Expressions
If we are going to keep this I think `expression` should be renamed to `expressions`.

```javascript
const s = carto.style.expressions;
const style = new carto.Style({
  color: s.ramp(s.jenks(s.prop('price'), s.float(3)), s.PRISM)
});
```

But having expresions as style child make sense to me:

```javascript
const s = carto.style;
const style = new carto.Style({
  color: s.ramp(s.jenks(s.prop('price'), s.float(3)), s.PRISM)
});
```

thoughts?

**Comment by Jesus89** [comment]
About singular/plural we used the "singular" convention for all the objects, in this case `carto.style.expression`. All the ramp, jenks, float functions are expressions, so I think it could be confusing to add this in the carto.style namespace because they are not style objects.

Using the expressions API the user will always create an aux variable to use it, so I think there is no problem keeping the complete name `carto.style.expression`.

**Comment by Jesus89** [comment]
Closed by: https://github.com/CartoDB/renderer-prototype/pull/74 :rocket:
