### ISSUE TITLE
Ramp: unexpected results

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/renderer-prototype#66]
After talking with @makella it's been clear that `ramp()` applies the cartocolor palettes in an "unexpected" way.

I would like confirmation about how this should be managed before implementing it. I think there are multiple issues with `ramp()` so I'm just gonna propose the future behavior.

Forgive me for the programmer-like way of asking this but I hope it's the clearest way to define the expected behavior. 
```
if palette is cartocolor then
          if input contains "others" bucket  then
                 apply cartocolor subscheme
          else if input doesn't contain ''others" bucket then
                  if cartocolor has "qualitative" tag then
                         apply cartocolor subscheme with one extra bucket to ignore the last bucket
                  else if cartocolor doesn't have "qualitative" tag then
                        apply cartocolor subscheme

```
```
if input is numeric then
     activate linear interpolation between colors, taking the cartocolor with most buckets
else if input is category then
      don't activate linear interpolation between colors
```

**Comment by makella** [comment]
@davidmanzanares I can't provide much technical detail, but we did experience something similar with TurboCARTO (not sure if it is at ALL related! but wanted to share nonetheless.)
https://github.com/CartoDB/turbo-carto/issues/38

**Comment by davidmanzanares** [comment]
I hope this is fixed.

cc: @makella

**Comment by makella** [comment]
@davidmanzanares 
from what i can see with a few tests, i'm no longer seeing the interpolation between category colors.

i am, however, seeing a different issue that i'll open a separate ticket for!

**Comment by makella** [comment]
@davidmanzanares I take that back! 

Illustrated below:

Using this styling:

`color: ramp(buckets($cause_descrip,"Lightning","Arson"),Prism)`

I am coloring 2 categories with `buckets` using `Prism`: 

<img width="230" alt="screen shot 2018-02-23 at 10 23 32 am" src="https://user-images.githubusercontent.com/1566273/36610539-80b67d0a-1885-11e8-9ba1-ae23bd81bdb8.png">

I would expect that features that are not in those two categories get pushed to the neutral gray color (11th color) that is part of every category scheme.

Instead, every other feature is getting colored with the third color in the scheme:

[Result](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoiZmlyZV9wZXJpbWV0ZXJfY2VudHJvaWRzIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiA4XG5jb2xvcjogcmFtcChidWNrZXRzKCRjYXVzZV9kZXNjcmlwLFwiTGlnaHRuaW5nXCIsXCJBcnNvblwiKSxQcmlzbSlcbnN0cm9rZVdpZHRoOiAxXG5zdHJva2VDb2xvcjogaHN2KDAsMCwwKVxuXG5cblxuXG4iLCJmIjp7ImxuZyI6LTExNi4yNTU1MzUzNTg4MjkyLCJsYXQiOjM3Ljg0OTMxNTk0ODc2ODgyfSwiZyI6NC45NjI3NDM5MjE2MjQxMzV9) 

The reason we would want to send everything else to the "other" gray is because this is a case where a user may want to highlight multiple category types in the data while pushing everything else to the background.

That is how we do it in Builder:

`  marker-fill: ramp([cause_descrip], cartocolor(Prism), ("Lightning","Arson"), "=");`

Results in [this map](https://team.carto.com/u/mamataakella/builder/c165576f-dbf0-40d6-a34d-1b06900b11c1/embed)

**Comment by makella** [comment]
@davidmanzanares tested over a couple of examples, and looks to be fixed! thanks!
